### ISSUE TITLE
peer to peer code review 2023-05-09

### ISSUE THREAD

**Issue by yashodhicy** [mohametalmeari/To-Do-List-Project#10]
hi @mohametalmeari  you have done a great job on your project, especially with extra features.

**Comment by yashodhicy** [comment]
It is better if you can use `todolist.foreach( )` loop for a better clean code.

**Comment by rachaouldbabaali** [comment]
Excellent progress so far! 👌 Everything is functioning flawlessly. However, I would suggest including a drag-and-drop icon to inform the user that they can adjust the order of tasks.
